# Approach:2 - with Python

In [1]:
#Importing the necessary libraries for data manipulation and analysis

import pandas as pd

In [2]:
# Reading the CSV file into a dataframe
file_path = 'C:/Users/Lenovo/Downloads/Iris.csv'
iris_df = pd.read_csv(file_path)

# Display the first few rows of the dataframe
iris_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
# Selecting petal length and sepal length
selected_df = iris_df[['PetalLengthCm', 'SepalLengthCm']]

# Display the first few rows of the selected dataframe
selected_df.head()

   PetalLengthCm  SepalLengthCm
0            1.4            5.1
1            1.4            4.9
2            1.3            4.7
3            1.5            4.6
4            1.4            5.0

In [4]:
# Filtering data for flowers with petal length more than 5.5 units
filtered_df = iris_df[iris_df['PetalLengthCm'] > 5.5]

# Display the first few rows of the filtered dataframe
filtered_df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica

In [5]:
# Creating the new column ‘flower area’
filtered_df['flower_area'] = filtered_df['PetalLengthCm'] * filtered_df['PetalWidthCm']

# Display the first few rows to check the new column
filtered_df.head()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2232\1656119469.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['flower_area'] = filtered_df['PetalLengthCm'] * filtered_df['PetalWidthCm']

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,flower_area
100,101,6.3,3.3,6.0,2.5,Iris-virginica,15.00
102,103,7.1,3.0,5.9,2.1,Iris-virginica,12.39
103,104,6.3,2.9,5.6,1.8,Iris-virginica,10.08
104,105,6.5,3.0,5.8,2.2,Iris-virginica,12.76
105,106,7.6,3.0,6.6,2.1,Iris-virginica,13.86

In [9]:
print("Filtered DataFrame with the new 'flower area' column:")
filtered_df

Filtered DataFrame with the new 'flower area' column:

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,flower_area
100,101,6.3,3.3,6.0,2.5,Iris-virginica,15.00
102,103,7.1,3.0,5.9,2.1,Iris-virginica,12.39
103,104,6.3,2.9,5.6,1.8,Iris-virginica,10.08
104,105,6.5,3.0,5.8,2.2,Iris-virginica,12.76
105,106,7.6,3.0,6.6,2.1,Iris-virginica,13.86
107,108,7.3,2.9,6.3,1.8,Iris-virginica,11.34
108,109,6.7,2.5,5.8,1.8,Iris-virginica,10.44
109,110,7.2,3.6,6.1,2.5,Iris-virginica,15.25
117,118,7.7,3.8,6.7,2.2,Iris-virginica,14.74
118,119,7.7,2.6,6.9,2.3,Iris-virginica,15.87
120,121,6.9,3.2,5.7,2.3,Iris-virginica,13.11
122,123,7.7,2.8,6.7,2.0,Iris-virginica,13.40
124,125,6.7,3.3,5.7,2.1,Iris-virginica,11.97
125,126,7.2,3.2,6.0,1.8,Iris-virginica,10.80
128,129,6.4,2.8,5.6,2.1,Iris-virginica,11.76
129,130,7.2,3.0,5.8,1.6,Iris-virginica,9.28
130,131,7.4,2.8,6.1,1.9,Iris-virginica,11.59
131,132,7.9,3.8,6.4,2.0,Iris-virginica,12.80
132,133,6.4,2.8,5.6,2.2,Iris-virginica,12.32
134,135,6.1,2.6,5.6,1.4,Iris-virginica,7.84
135,136,7.7,3.0,6.1,2.3,Iris-virginica,14.03
136,137,6.3,3.4,5.6,2.4,Iris-virginica,13.44
140,141,6.7,3.1,5.6,2.4,Iris-virginica,13.44
143,144,6.8,3.2,5.9,2.3,Iris-virginica,13.57
144,145,6.7,3.3,5.7,2.5,Iris-virginica,14.25